import { describe, it, expect } from 'vitest';
import { Chess } from 'chess.js';
import {
    encodePersistedBlob,
    decodePersistedBlob,
    hashFen,
    _murmur3_x86_128_hex,
    PERSISTED_BLOB_VERSION,
    PersistedBlobV2,
} from './BlobCodec';
import { RepertoireData } from '../models/RepertoireData';
import { RepertoireEntry, PositionEntry } from '../models/Repertoires';
import { FSRSCardData } from '../models/FSRSCardData';
import { normalizeFenResetHalfmoveClock } from './FenUtils';

const startFen = (): string => normalizeFenResetHalfmoveClock(new Chess().fen());

const fenAfter = (sans: string[]): string => {
    const c = new Chess();
    for (const san of sans) c.move(san);
    return normalizeFenResetHalfmoveClock(c.fen());
};

function reviewCard(overrides: Partial<FSRSCardData> = {}): FSRSCardData {
    return {
        d: '2030-01-01T12:34:56.789Z',
        s: 12.5,
        di: 4.2,
        e: 3,
        sd: 7,
        ls: 0,
        r: 8,
        l: 1,
        st: 2,
        lr: '2026-04-19T08:00:00.500Z',
        ...overrides,
    };
}

function newCard(): FSRSCardData {
    return { d: '2026-01-01T00:00:00.000Z', s: 0, di: 0, e: 0, sd: 0, ls: 0, r: 0, l: 0, st: 0 };
}

function whiteRep(positions: Record<string, PositionEntry>): RepertoireEntry {
    return { name: 'White', orientation: 'white', positions };
}
function blackRep(positions: Record<string, PositionEntry> = {}): RepertoireEntry {
    return { name: 'Black', orientation: 'black', positions };
}

function baseData(reps: RepertoireEntry[]): RepertoireData {
    return {
        repertoires: reps,
        currentEpoch: 0,
        lastPlayedDate: new Date('2026-05-25T00:00:00.000Z'),
        dailyPlayCount: 0,
    };
}

describe('BlobCodec', () => {
    describe('hashFen', () => {
        it('produces a 12-char base64url string', async () => {
            const h = hashFen(startFen());
            expect(h).toHaveLength(12);
            expect(h).toMatch(/^[A-Za-z0-9_-]{12}$/);
        });

        it('is deterministic for the same FEN', async () => {
            const a = hashFen(startFen());
            const b = hashFen(startFen());
            expect(a).toBe(b);
        });

        it('produces different hashes for different FENs', async () => {
            const a = hashFen(startFen());
            const b = hashFen(fenAfter(['e4']));
            expect(a).not.toBe(b);
        });
    });

    describe('MurmurHash3 x86_128 — verified against murmurhash3js@3.0.1', () => {
        // Reference vectors generated by:
        //   require('murmurhash3js').x86.hash128(input, 0)
        // (output is 32-char big-endian hex of [h1, h2, h3, h4])
        const VECTORS: Array<[string, string]> = [
            ['', '00000000000000000000000000000000'],
            ['a', 'a794933c5556b01b5556b01b5556b01b'],
            ['ab', '158451df25be301025be301025be3010'],
            ['abc', '75cdc6d1a2b006a5a2b006a5a2b006a5'],
            ['abcd', '96b6ccaa45afc62e45afc62e45afc62e'],
            ['1234567890123456', '203ddfb819f43d833f40b44cd2d7a0bd'],          // exact 16 bytes (one full block, no tail)
            ['12345678901234567', '43418b6f6ce2409e9d9e3142409a807c'],         // 16 + 1 tail
            ['rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', 'a8ac20657803120eac6c8f6a363a7a17'],
            ['r1bqkbnr/pp1ppppp/2n5/2p5/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 3', 'c1a16b009a62d9c7118f6743b2318de5'],
        ];

        for (const [input, expected] of VECTORS) {
            it(`hash128(${JSON.stringify(input)}) matches reference`, () => {
                expect(_murmur3_x86_128_hex(input)).toBe(expected);
            });
        }
    });

    describe('encode → decode round-trip', () => {
        it('round-trips a simple White repertoire with one user-turn card', async () => {
            const root = startFen();
            const data = baseData([
                whiteRep({
                    [root]: { moves: { e4: { card: reviewCard() } } },
                    [fenAfter(['e4'])]: { moves: {} },
                }),
                blackRep(),
            ]);

            const enc = encodePersistedBlob(data);
            const json = JSON.parse(JSON.stringify(enc));
            const dec = decodePersistedBlob(json);

            const w = dec.repertoires!.find(r => r.orientation === 'white')!;
            expect(w.positions[root].moves.e4.card).toEqual(reviewCard());
            expect(w.positions[fenAfter(['e4'])]).toEqual({ moves: {} });
            const b = dec.repertoires!.find(r => r.orientation === 'black')!;
            expect(b.positions).toEqual({});
        });

        it('round-trips an opponent move (empty envelope)', async () => {
            const root = startFen();
            const data = baseData([
                whiteRep({
                    [root]: { moves: { e4: { card: reviewCard() } } },
                    [fenAfter(['e4'])]: { moves: { e5: {} } },           // Black to move — opponent
                    [fenAfter(['e4', 'e5'])]: { moves: {} },
                }),
                blackRep(),
            ]);

            const enc = encodePersistedBlob(data);
            const dec = decodePersistedBlob(JSON.parse(JSON.stringify(enc)));
            const w = dec.repertoires!.find(r => r.orientation === 'white')!;
            expect(w.positions[fenAfter(['e4'])].moves.e5).toEqual({});
        });

        it('round-trips position-level annotations', async () => {
            const root = startFen();
            const data = baseData([
                whiteRep({
                    [root]: {
                        annotations: [
                            { brush: 'G', orig: 'e2', dest: 'e4' },
                            { brush: 'R', orig: 'e5' },
                        ],
                        moves: { e4: { card: reviewCard() } },
                    },
                    [fenAfter(['e4'])]: { moves: {} },
                }),
                blackRep(),
            ]);

            const dec = decodePersistedBlob(
                JSON.parse(JSON.stringify(encodePersistedBlob(data)))
            );
            const w = dec.repertoires!.find(r => r.orientation === 'white')!;
            expect(w.positions[root].annotations).toEqual([
                { brush: 'G', orig: 'e2', dest: 'e4' },
                { brush: 'R', orig: 'e5' },
            ]);
        });

        it('round-trips a card WITHOUT lr (length-9 packed array)', async () => {
            const root = startFen();
            const c = newCard();
            const data = baseData([
                whiteRep({
                    [root]: { moves: { e4: { card: c } } },
                    [fenAfter(['e4'])]: { moves: {} },
                }),
                blackRep(),
            ]);
            const enc = encodePersistedBlob(data);
            const move = enc.repertoires[0].positions[hashFen(root)].moves.e4;
            expect(move.card).toHaveLength(9);
            const dec = decodePersistedBlob(JSON.parse(JSON.stringify(enc)));
            const w = dec.repertoires!.find(r => r.orientation === 'white')!;
            expect(w.positions[root].moves.e4.card).toEqual(c);
        });

        it('preserves epoch-ms precision on lr', async () => {
            const root = startFen();
            const c = reviewCard({ lr: '2026-04-19T08:00:00.123Z' });
            const data = baseData([
                whiteRep({
                    [root]: { moves: { e4: { card: c } } },
                    [fenAfter(['e4'])]: { moves: {} },
                }),
                blackRep(),
            ]);
            const dec = decodePersistedBlob(
                JSON.parse(JSON.stringify(encodePersistedBlob(data)))
            );
            const w = dec.repertoires!.find(r => r.orientation === 'white')!;
            expect(w.positions[root].moves.e4.card!.lr).toBe('2026-04-19T08:00:00.123Z');
        });

        it('round-trips deeper lines with transpositions (cycle-safe walk)', async () => {
            // 1.Nf3 Nf6 2.Ng1 Ng8 transposes back to the standard start FEN.
            const root = startFen();
            const data = baseData([
                whiteRep({
                    [root]: { moves: { Nf3: { card: reviewCard() } } },
                    [fenAfter(['Nf3'])]: { moves: { Nf6: {} } },
                    [fenAfter(['Nf3', 'Nf6'])]: { moves: { Ng1: { card: reviewCard() } } },
                    [fenAfter(['Nf3', 'Nf6', 'Ng1'])]: { moves: { Ng8: {} } },
                    // 1.Nf3 Nf6 2.Ng1 Ng8 → back to root; the cycle must not loop.
                }),
                blackRep(),
            ]);
            const dec = decodePersistedBlob(
                JSON.parse(JSON.stringify(encodePersistedBlob(data)))
            );
            const w = dec.repertoires!.find(r => r.orientation === 'white')!;
            // root should still appear exactly once and carry only its own moves.
            expect(Object.keys(w.positions[root].moves).sort()).toEqual(['Nf3']);
            expect(w.positions[fenAfter(['Nf3', 'Nf6', 'Ng1'])].moves.Ng8).toEqual({});
        });

        it('round-trips a Black repertoire with an opponent-first-move shape', async () => {
            const root = startFen();
            const data = baseData([
                whiteRep({}),
                blackRep({
                    [root]: { moves: { e4: {} } },                       // White to move — opponent
                    [fenAfter(['e4'])]: { moves: { c5: { card: reviewCard() } } },
                    [fenAfter(['e4', 'c5'])]: { moves: {} },
                }),
            ]);
            const dec = decodePersistedBlob(
                JSON.parse(JSON.stringify(encodePersistedBlob(data)))
            );
            const b = dec.repertoires!.find(r => r.orientation === 'black')!;
            expect(b.positions[fenAfter(['e4'])].moves.c5.card).toEqual(reviewCard());
        });

        it('preserves currentEpoch / lastPlayedDate / dailyPlayCount / settings / activity / games', async () => {
            const root = startFen();
            const data: RepertoireData = {
                ...baseData([
                    whiteRep({
                        [root]: { moves: { e4: { card: reviewCard() } } },
                        [fenAfter(['e4'])]: { moves: {} },
                    }),
                    blackRep(),
                ]),
                settings: { contextDepth: 4, retention: 0.97 },
                activity: {
                    practiceLog: [
                        { date: '2026-05-25', reviewed: 10, mistakes: 2, learned: 1, traversals: 3, timeSeconds: 300 },
                    ],
                    lifetime: { reviewed: 100, mistakes: 20, learned: 10, traversals: 50, timeSeconds: 5000 },
                },
                games: { 'lichess:foo': { watermarkMs: 1234567890123, recentIds: [{ id: 'g1', ts: 1234567890000 }] } },
            };
            const enc = encodePersistedBlob(data);
            const json = JSON.parse(JSON.stringify(enc));
            const dec = decodePersistedBlob(json);

            expect(dec.currentEpoch).toBe(0);
            expect(String(dec.lastPlayedDate)).toBe('2026-05-25T00:00:00.000Z');
            expect(dec.dailyPlayCount).toBe(0);
            expect(dec.settings?.contextDepth).toBe(4);
            expect(dec.activity?.practiceLog).toHaveLength(1);
            expect(dec.games?.['lichess:foo'].watermarkMs).toBe(1234567890123);
            // Ensure watermarkMs / recentIds[].ts kept millisecond precision.
            expect(dec.games?.['lichess:foo'].recentIds[0]).toEqual({ id: 'g1', ts: 1234567890000 });
        });
    });

    describe('encode shape', () => {
        it('stamps the version flag and uses hashed keys', async () => {
            const root = startFen();
            const data = baseData([
                whiteRep({
                    [root]: { moves: { e4: { card: reviewCard() } } },
                    [fenAfter(['e4'])]: { moves: {} },
                }),
                blackRep(),
            ]);
            const enc = encodePersistedBlob(data);
            expect(enc.v).toBe(PERSISTED_BLOB_VERSION);
            const rootHash = hashFen(root);
            expect(Object.keys(enc.repertoires[0].positions)).toContain(rootHash);
            // Hashed key, NOT the full FEN.
            expect(Object.keys(enc.repertoires[0].positions).some(k => k.includes('/'))).toBe(false);
        });

        it('packs cards as 9- or 10-element arrays', async () => {
            const root = startFen();
            const withLr = reviewCard();
            const noLr = newCard();
            const data = baseData([
                whiteRep({
                    [root]: { moves: { e4: { card: withLr }, d4: { card: noLr } } },
                    [fenAfter(['e4'])]: { moves: {} },
                    [fenAfter(['d4'])]: { moves: {} },
                }),
                blackRep(),
            ]);
            const enc = encodePersistedBlob(data);
            const rootHash = hashFen(root);
            const moves = enc.repertoires[0].positions[rootHash].moves;
            expect(moves.e4.card).toHaveLength(10);
            expect(moves.d4.card).toHaveLength(9);
            // First element is epoch ms, an integer
            expect(typeof (moves.e4.card as number[])[0]).toBe('number');
            expect(Number.isInteger((moves.e4.card as number[])[0])).toBe(true);
        });
    });

    describe('error paths', () => {
        it('encode throws on orphan position (unreachable from initial FEN)', async () => {
            const root = startFen();
            // A position reachable via 1.e4 e5 but its parent (after 1.e4) is missing
            // from the dict — so the walk from root cannot reach it.
            const data = baseData([
                whiteRep({
                    [root]: { moves: { e4: { card: reviewCard() } } },
                    // NOTE: `fenAfter(['e4'])` is intentionally missing.
                    [fenAfter(['e4', 'e5'])]: { moves: {} },
                }),
                blackRep(),
            ]);
            expect(() => encodePersistedBlob(data)).toThrow(/orphan position/);
        });

        it('encode throws on a SAN that cannot be replayed (broken graph)', async () => {
            const root = startFen();
            const data = baseData([
                whiteRep({
                    [root]: { moves: { Zz9: { card: reviewCard() } } },  // bogus SAN — no child reachable
                    [fenAfter(['e4'])]: { moves: {} },                     // therefore this is an orphan
                }),
                blackRep(),
            ]);
            expect(() => encodePersistedBlob(data)).toThrow(/orphan position/);
        });

        it('decode throws on unsupported version', async () => {
            const blob = { v: 99, repertoires: [], currentEpoch: 0, lastPlayedDate: '', dailyPlayCount: 0 };
            expect(() => decodePersistedBlob(blob)).toThrow(/unsupported repertoire blob version/i);
        });

        it('decode throws when a persisted hash is unreachable from start', async () => {
            // Build a v2 blob by hand with an orphan hashed entry.
            const root = startFen();
            const rootHash = hashFen(root);
            const orphanHash = hashFen(fenAfter(['e4', 'e5']));
            const blob: PersistedBlobV2 = {
                v: PERSISTED_BLOB_VERSION,
                repertoires: [
                    {
                        name: 'White', orientation: 'white',
                        positions: {
                            [rootHash]: { moves: { e4: { card: [Date.parse('2030-01-01'), 0, 0, 0, 0, 0, 0, 0, 0] } } },
                            // `fenAfter(['e4'])` hash intentionally absent — walk stops there
                            // so orphanHash is unreachable.
                            [orphanHash]: { moves: {} },
                        },
                    },
                    { name: 'Black', orientation: 'black', positions: {} },
                ],
                currentEpoch: 0,
                lastPlayedDate: '2026-05-25T00:00:00.000Z',
                dailyPlayCount: 0,
            };
            expect(() => decodePersistedBlob(blob)).toThrow(/orphan persisted entry/);
        });

        it('decode throws on malformed packed card', async () => {
            const root = startFen();
            const rootHash = hashFen(root);
            const blob: PersistedBlobV2 = {
                v: PERSISTED_BLOB_VERSION,
                repertoires: [
                    {
                        name: 'White', orientation: 'white',
                        positions: {
                            [rootHash]: { moves: { e4: { card: [1, 2, 3] as unknown as never } } },
                            [hashFen(fenAfter(['e4']))]: { moves: {} },
                        },
                    },
                    { name: 'Black', orientation: 'black', positions: {} },
                ],
                currentEpoch: 0, lastPlayedDate: '', dailyPlayCount: 0,
            };
            expect(() => decodePersistedBlob(blob)).toThrow(/malformed packed card/);
        });

        // Each non-finite value below would crash with "RangeError: Invalid time value"
        // (from `new Date(...).toISOString()`) without an explicit guard — that error
        // gives the caller no clue where the bad data came from. The dedicated
        // "malformed packed card" message names the offending element index and value.
        for (const badValue of [NaN, Infinity, -Infinity, null, undefined, '123', true]) {
            it(`decode throws "malformed packed card" on non-finite element (${
                JSON.stringify(badValue)
            }) instead of "Invalid time value"`, () => {
                const root = startFen();
                const rootHash = hashFen(root);
                // d (element 0) is non-finite; rest are valid
                const card = [badValue, 1, 1, 0, 1, 0, 1, 0, 2] as unknown as never;
                const blob: PersistedBlobV2 = {
                    v: PERSISTED_BLOB_VERSION,
                    repertoires: [
                        {
                            name: 'White', orientation: 'white',
                            positions: {
                                [rootHash]: { moves: { e4: { card } } },
                                [hashFen(fenAfter(['e4']))]: { moves: {} },
                            },
                        },
                        { name: 'Black', orientation: 'black', positions: {} },
                    ],
                    currentEpoch: 0, lastPlayedDate: '', dailyPlayCount: 0,
                };
                expect(() => decodePersistedBlob(blob)).toThrow(/malformed packed card.*element 0/);
            });
        }

        it('decode throws "malformed packed card" with the offending element index for lr (element 9)', () => {
            const root = startFen();
            const rootHash = hashFen(root);
            const card = [Date.parse('2030-01-01'), 1, 1, 0, 1, 0, 1, 0, 2, NaN] as unknown as never;
            const blob: PersistedBlobV2 = {
                v: PERSISTED_BLOB_VERSION,
                repertoires: [
                    {
                        name: 'White', orientation: 'white',
                        positions: {
                            [rootHash]: { moves: { e4: { card } } },
                            [hashFen(fenAfter(['e4']))]: { moves: {} },
                        },
                    },
                    { name: 'Black', orientation: 'black', positions: {} },
                ],
                currentEpoch: 0, lastPlayedDate: '', dailyPlayCount: 0,
            };
            expect(() => decodePersistedBlob(blob)).toThrow(/malformed packed card.*element 9/);
        });
    });

    describe('v1 pass-through', () => {
        it('returns the raw object unchanged when `v` is absent', async () => {
            const v1: RepertoireData = {
                data: [],
                currentEpoch: 0,
                lastPlayedDate: new Date('2026-05-25T00:00:00.000Z'),
                dailyPlayCount: 0,
            };
            const out = decodePersistedBlob(v1);
            expect(out).toBe(v1);
        });

        it('returns a v1 position-centric blob (with `repertoires`, no `v`) unchanged', async () => {
            const v1: RepertoireData = {
                repertoires: [
                    {
                        name: 'White', orientation: 'white',
                        positions: { [startFen()]: { moves: { e4: { card: reviewCard() } } } },
                    },
                    { name: 'Black', orientation: 'black', positions: {} },
                ],
                currentEpoch: 0,
                lastPlayedDate: new Date('2026-05-25T00:00:00.000Z'),
                dailyPlayCount: 0,
            };
            const out = decodePersistedBlob(v1);
            expect(out).toBe(v1);
        });
    });

    describe('empty cases', () => {
        it('encodes/decodes a fully empty repertoire pair', async () => {
            const data = baseData([whiteRep({}), blackRep({})]);
            const enc = encodePersistedBlob(data);
            expect(enc.v).toBe(PERSISTED_BLOB_VERSION);
            expect(enc.repertoires[0].positions).toEqual({});
            expect(enc.repertoires[1].positions).toEqual({});
            const dec = decodePersistedBlob(JSON.parse(JSON.stringify(enc)));
            expect(dec.repertoires).toHaveLength(2);
            expect(dec.repertoires![0].positions).toEqual({});
            expect(dec.repertoires![1].positions).toEqual({});
        });

        it('encodes a leaf position with annotations and no moves', async () => {
            const root = startFen();
            const data = baseData([
                whiteRep({
                    [root]: { moves: { e4: { card: reviewCard() } } },
                    [fenAfter(['e4'])]: {
                        annotations: [{ brush: 'B', orig: 'd5' }],
                        moves: {},
                    },
                }),
                blackRep(),
            ]);
            const enc = encodePersistedBlob(data);
            const dec = decodePersistedBlob(JSON.parse(JSON.stringify(enc)));
            const w = dec.repertoires!.find(r => r.orientation === 'white')!;
            expect(w.positions[fenAfter(['e4'])].annotations).toEqual([{ brush: 'B', orig: 'd5' }]);
            expect(w.positions[fenAfter(['e4'])].moves).toEqual({});
        });
    });
});
