name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: app/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('app/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies with Yarn
        run: yarn install
        working-directory: app

      - name: Run tests
        run: yarn test
        working-directory: app

      # If tests pass, do a build
      - name: Build
        run: yarn build
        working-directory: app

      - name: Configure git user
        # This ensures gh-pages can commit with a known identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
        working-directory: app

      # Deploy only if tests & build succeeded
      - name: Deploy to GitHub Pages
        if: ${{ success() }}  # Only run if previous step succeeded
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
